--
-- PostgreSQL database dump
--

-- Dumped from database version 15.8 (Debian 15.8-0+deb12u1)
-- Dumped by pg_dump version 15.8 (Debian 15.8-0+deb12u1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: hstore; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS hstore WITH SCHEMA public;


--
-- Name: EXTENSION hstore; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION hstore IS 'data type for storing sets of (key, value) pairs';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: clokwise
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO clokwise;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: clokwise
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: clokwise
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO clokwise;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: clokwise
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: clokwise
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO clokwise;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: clokwise
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: chats_attachment; Type: TABLE; Schema: public; Owner: clokwise
--

CREATE TABLE public.chats_attachment (
    id bigint NOT NULL,
    uuid uuid NOT NULL,
    mime_type character varying(128) NOT NULL,
    file character varying(100) NOT NULL,
    chat_id bigint,
    creator_id bigint NOT NULL,
    type character varying(64) NOT NULL,
    filename character varying(1024)
);


ALTER TABLE public.chats_attachment OWNER TO clokwise;

--
-- Name: chats_attachment_id_seq; Type: SEQUENCE; Schema: public; Owner: clokwise
--

ALTER TABLE public.chats_attachment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chats_attachment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: chats_chat; Type: TABLE; Schema: public; Owner: clokwise
--

CREATE TABLE public.chats_chat (
    id bigint NOT NULL,
    datetime_created timestamp with time zone NOT NULL,
    search_request_id bigint,
    initiator_id bigint,
    is_closed boolean NOT NULL,
    expert_id bigint,
    is_support boolean NOT NULL
);


ALTER TABLE public.chats_chat OWNER TO clokwise;

--
-- Name: chats_chat_confirmations; Type: TABLE; Schema: public; Owner: clokwise
--

CREATE TABLE public.chats_chat_confirmations (
    id bigint NOT NULL,
    chat_id bigint NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.chats_chat_confirmations OWNER TO clokwise;

--
-- Name: chats_chat_confirmations_id_seq; Type: SEQUENCE; Schema: public; Owner: clokwise
--

ALTER TABLE public.chats_chat_confirmations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chats_chat_confirmations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: chats_chat_id_seq; Type: SEQUENCE; Schema: public; Owner: clokwise
--

ALTER TABLE public.chats_chat ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chats_chat_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: chats_chat_participants; Type: TABLE; Schema: public; Owner: clokwise
--

CREATE TABLE public.chats_chat_participants (
    id bigint NOT NULL,
    chat_id bigint NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.chats_chat_participants OWNER TO clokwise;

--
-- Name: chats_chat_participants_id_seq; Type: SEQUENCE; Schema: public; Owner: clokwise
--

ALTER TABLE public.chats_chat_participants ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chats_chat_participants_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: chats_message; Type: TABLE; Schema: public; Owner: clokwise
--

CREATE TABLE public.chats_message (
    id bigint NOT NULL,
    text text,
    datetime_created timestamp with time zone NOT NULL,
    chat_id bigint NOT NULL,
    from_user_id bigint NOT NULL,
    available_until timestamp with time zone,
    is_deleted boolean NOT NULL,
    datetime_edited timestamp with time zone NOT NULL
);


ALTER TABLE public.chats_message OWNER TO clokwise;

--
-- Name: chats_message_attachments; Type: TABLE; Schema: public; Owner: clokwise
--

CREATE TABLE public.chats_message_attachments (
    id bigint NOT NULL,
    message_id bigint NOT NULL,
    attachment_id bigint NOT NULL
);


ALTER TABLE public.chats_message_attachments OWNER TO clokwise;

--
-- Name: chats_message_attachments_id_seq; Type: SEQUENCE; Schema: public; Owner: clokwise
--

ALTER TABLE public.chats_message_attachments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chats_message_attachments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: chats_message_id_seq; Type: SEQUENCE; Schema: public; Owner: clokwise
--

ALTER TABLE public.chats_message ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chats_message_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: chats_messagereadtime; Type: TABLE; Schema: public; Owner: clokwise
--

CREATE TABLE public.chats_messagereadtime (
    id bigint NOT NULL,
    datetime_read timestamp with time zone NOT NULL,
    message_id bigint NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.chats_messagereadtime OWNER TO clokwise;

--
-- Name: chats_messagereadtime_id_seq; Type: SEQUENCE; Schema: public; Owner: clokwise
--

ALTER TABLE public.chats_messagereadtime ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chats_messagereadtime_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: clokwise
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO clokwise;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: clokwise
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: clokwise
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO clokwise;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: clokwise
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: clokwise
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO clokwise;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: clokwise
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: clokwise
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO clokwise;

--
-- Name: drf_attachments_attachment; Type: TABLE; Schema: public; Owner: clokwise
--

CREATE TABLE public.drf_attachments_attachment (
    id uuid NOT NULL,
    name character varying(255) NOT NULL,
    context character varying(255) NOT NULL,
    meta jsonb NOT NULL,
    file character varying(100) NOT NULL,
    object_id character varying(64) NOT NULL,
    creation_date timestamp with time zone NOT NULL,
    last_modification_date timestamp with time zone NOT NULL,
    content_type_id integer NOT NULL
);


ALTER TABLE public.drf_attachments_attachment OWNER TO clokwise;

--
-- Name: fcm_django_fcmdevice; Type: TABLE; Schema: public; Owner: clokwise
--

CREATE TABLE public.fcm_django_fcmdevice (
    id integer NOT NULL,
    name character varying(255),
    active boolean NOT NULL,
    date_created timestamp with time zone,
    device_id character varying(255),
    registration_id text NOT NULL,
    type character varying(10) NOT NULL,
    user_id bigint
);


ALTER TABLE public.fcm_django_fcmdevice OWNER TO clokwise;

--
-- Name: fcm_django_fcmdevice_id_seq; Type: SEQUENCE; Schema: public; Owner: clokwise
--

ALTER TABLE public.fcm_django_fcmdevice ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.fcm_django_fcmdevice_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_confirmationcode; Type: TABLE; Schema: public; Owner: clokwise
--

CREATE TABLE public.users_confirmationcode (
    id bigint NOT NULL,
    datetime_created timestamp with time zone NOT NULL,
    email character varying(254) NOT NULL,
    token character varying(128) NOT NULL,
    type character varying(64) NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.users_confirmationcode OWNER TO clokwise;

--
-- Name: users_confirmationcode_id_seq; Type: SEQUENCE; Schema: public; Owner: clokwise
--

ALTER TABLE public.users_confirmationcode ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_confirmationcode_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_educationdegree; Type: TABLE; Schema: public; Owner: clokwise
--

CREATE TABLE public.users_educationdegree (
    id bigint NOT NULL,
    name character varying(96) NOT NULL,
    order_number integer NOT NULL,
    CONSTRAINT users_educationdegree_order_number_check CHECK ((order_number >= 0))
);


ALTER TABLE public.users_educationdegree OWNER TO clokwise;

--
-- Name: users_educationdegree_id_seq; Type: SEQUENCE; Schema: public; Owner: clokwise
--

ALTER TABLE public.users_educationdegree ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_educationdegree_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_educationlevel; Type: TABLE; Schema: public; Owner: clokwise
--

CREATE TABLE public.users_educationlevel (
    id bigint NOT NULL,
    name character varying(96) NOT NULL,
    order_number integer NOT NULL,
    CONSTRAINT users_educationlevel_order_number_check CHECK ((order_number >= 0))
);


ALTER TABLE public.users_educationlevel OWNER TO clokwise;

--
-- Name: users_educationlevel_id_seq; Type: SEQUENCE; Schema: public; Owner: clokwise
--

ALTER TABLE public.users_educationlevel ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_educationlevel_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_experienceclassificator; Type: TABLE; Schema: public; Owner: clokwise
--

CREATE TABLE public.users_experienceclassificator (
    id bigint NOT NULL,
    name character varying(96) NOT NULL,
    type character varying(64) NOT NULL,
    order_number integer NOT NULL,
    parent_id bigint,
    CONSTRAINT users_experienceclassificator_order_number_check CHECK ((order_number >= 0))
);


ALTER TABLE public.users_experienceclassificator OWNER TO clokwise;

--
-- Name: users_experienceclassificator_id_seq; Type: SEQUENCE; Schema: public; Owner: clokwise
--

ALTER TABLE public.users_experienceclassificator ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_experienceclassificator_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_experteducationrecord; Type: TABLE; Schema: public; Owner: clokwise
--

CREATE TABLE public.users_experteducationrecord (
    id bigint NOT NULL,
    institution_name character varying(256) NOT NULL,
    speciality_name character varying(256) NOT NULL,
    education_degree_id bigint,
    education_level_id bigint NOT NULL,
    user_id bigint NOT NULL,
    department_name character varying(256) NOT NULL
);


ALTER TABLE public.users_experteducationrecord OWNER TO clokwise;

--
-- Name: users_experteducationrecord_id_seq; Type: SEQUENCE; Schema: public; Owner: clokwise
--

ALTER TABLE public.users_experteducationrecord ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_experteducationrecord_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_expertexperiencerecord; Type: TABLE; Schema: public; Owner: clokwise
--

CREATE TABLE public.users_expertexperiencerecord (
    id bigint NOT NULL,
    organization_name character varying(256) NOT NULL,
    date_start date NOT NULL,
    date_end date NOT NULL,
    "position" character varying(256) NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.users_expertexperiencerecord OWNER TO clokwise;

--
-- Name: users_expertexperiencerecord_id_seq; Type: SEQUENCE; Schema: public; Owner: clokwise
--

ALTER TABLE public.users_expertexperiencerecord ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_expertexperiencerecord_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_expertexperiencesegment; Type: TABLE; Schema: public; Owner: clokwise
--

CREATE TABLE public.users_expertexperiencesegment (
    id bigint NOT NULL,
    date_start date NOT NULL,
    date_end date NOT NULL,
    description text NOT NULL,
    experience_record_id bigint NOT NULL,
    function_id bigint NOT NULL,
    industry_id bigint NOT NULL,
    subfunction_id bigint NOT NULL,
    subindustry_id bigint NOT NULL
);


ALTER TABLE public.users_expertexperiencesegment OWNER TO clokwise;

--
-- Name: users_expertexperiencesegment_id_seq; Type: SEQUENCE; Schema: public; Owner: clokwise
--

ALTER TABLE public.users_expertexperiencesegment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_expertexperiencesegment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_expertsearchrequest; Type: TABLE; Schema: public; Owner: clokwise
--

CREATE TABLE public.users_expertsearchrequest (
    id bigint NOT NULL,
    name character varying(256) NOT NULL,
    datetime_created timestamp with time zone NOT NULL,
    description text,
    creator_id bigint NOT NULL,
    function_id bigint,
    industry_id bigint NOT NULL,
    subfunction_id bigint,
    subindustry_id bigint,
    datetime_expire timestamp with time zone DEFAULT (statement_timestamp() + '7 days'::interval) NOT NULL,
    is_active boolean NOT NULL,
    type character varying(64) NOT NULL
);


ALTER TABLE public.users_expertsearchrequest OWNER TO clokwise;

--
-- Name: users_expertsearchrequest_id_seq; Type: SEQUENCE; Schema: public; Owner: clokwise
--

ALTER TABLE public.users_expertsearchrequest ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_expertsearchrequest_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_expertsearchrequestexpertapplication; Type: TABLE; Schema: public; Owner: clokwise
--

CREATE TABLE public.users_expertsearchrequestexpertapplication (
    id bigint NOT NULL,
    datetime_created timestamp with time zone NOT NULL,
    expert_id bigint NOT NULL,
    request_id bigint NOT NULL
);


ALTER TABLE public.users_expertsearchrequestexpertapplication OWNER TO clokwise;

--
-- Name: users_expertsearchrequestexpertapplication_id_seq; Type: SEQUENCE; Schema: public; Owner: clokwise
--

ALTER TABLE public.users_expertsearchrequestexpertapplication ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_expertsearchrequestexpertapplication_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_notification; Type: TABLE; Schema: public; Owner: clokwise
--

CREATE TABLE public.users_notification (
    id bigint NOT NULL,
    header text,
    text text NOT NULL,
    datetime_created timestamp with time zone NOT NULL,
    url character varying(150),
    image character varying(200),
    type smallint NOT NULL,
    is_read boolean NOT NULL,
    is_active boolean NOT NULL,
    receiver_id bigint NOT NULL,
    sender_id bigint,
    other_data public.hstore,
    datetime_read timestamp with time zone,
    send_firebase_notification boolean NOT NULL,
    CONSTRAINT users_notification_type_check CHECK ((type >= 0))
);


ALTER TABLE public.users_notification OWNER TO clokwise;

--
-- Name: users_notification_id_seq; Type: SEQUENCE; Schema: public; Owner: clokwise
--

ALTER TABLE public.users_notification ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_notification_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_user; Type: TABLE; Schema: public; Owner: clokwise
--

CREATE TABLE public.users_user (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    first_name character varying(64) NOT NULL,
    last_name character varying(64) NOT NULL,
    email character varying(254),
    phone_number character varying(128),
    date_registered timestamp with time zone NOT NULL,
    is_verified_email boolean NOT NULL,
    company_description text,
    company_inn bigint,
    company_name character varying(128),
    company_website character varying(200),
    is_legal_entity boolean NOT NULL,
    person_activity_description text,
    person_website character varying(200),
    avatar_id bigint,
    is_company_info_verification_requested boolean NOT NULL,
    is_company_info_verified boolean NOT NULL,
    subscription_until timestamp with time zone,
    CONSTRAINT users_user_company_inn_check CHECK ((company_inn >= 0))
);


ALTER TABLE public.users_user OWNER TO clokwise;

--
-- Name: users_user_groups; Type: TABLE; Schema: public; Owner: clokwise
--

CREATE TABLE public.users_user_groups (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.users_user_groups OWNER TO clokwise;

--
-- Name: users_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: clokwise
--

ALTER TABLE public.users_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_user_id_seq; Type: SEQUENCE; Schema: public; Owner: clokwise
--

ALTER TABLE public.users_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_user_paid_users_for_view; Type: TABLE; Schema: public; Owner: clokwise
--

CREATE TABLE public.users_user_paid_users_for_view (
    id bigint NOT NULL,
    from_user_id bigint NOT NULL,
    to_user_id bigint NOT NULL
);


ALTER TABLE public.users_user_paid_users_for_view OWNER TO clokwise;

--
-- Name: users_user_paid_users_for_view_id_seq; Type: SEQUENCE; Schema: public; Owner: clokwise
--

ALTER TABLE public.users_user_paid_users_for_view ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_paid_users_for_view_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_user_user_permissions; Type: TABLE; Schema: public; Owner: clokwise
--

CREATE TABLE public.users_user_user_permissions (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.users_user_user_permissions OWNER TO clokwise;

--
-- Name: users_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: clokwise
--

ALTER TABLE public.users_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_useravatar; Type: TABLE; Schema: public; Owner: clokwise
--

CREATE TABLE public.users_useravatar (
    id bigint NOT NULL,
    image character varying(100) NOT NULL,
    image_small character varying(100) NOT NULL,
    is_preset boolean NOT NULL
);


ALTER TABLE public.users_useravatar OWNER TO clokwise;

--
-- Name: users_useravatar_id_seq; Type: SEQUENCE; Schema: public; Owner: clokwise
--

ALTER TABLE public.users_useravatar ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_useravatar_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_userreview; Type: TABLE; Schema: public; Owner: clokwise
--

CREATE TABLE public.users_userreview (
    id bigint NOT NULL,
    rating smallint,
    text text,
    type character varying(64) NOT NULL,
    reviewer_id bigint NOT NULL,
    user_id bigint NOT NULL,
    chat_id bigint,
    datetime_created timestamp with time zone,
    CONSTRAINT users_userreview_rating_check CHECK ((rating >= 0))
);


ALTER TABLE public.users_userreview OWNER TO clokwise;

--
-- Name: users_userreview_id_seq; Type: SEQUENCE; Schema: public; Owner: clokwise
--

ALTER TABLE public.users_userreview ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_userreview_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: clokwise
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: clokwise
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: clokwise
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: clokwise
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: clokwise
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: clokwise
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: chats_attachment chats_attachment_pkey; Type: CONSTRAINT; Schema: public; Owner: clokwise
--

ALTER TABLE ONLY public.chats_attachment
    ADD CONSTRAINT chats_attachment_pkey PRIMARY KEY (id);


--
-- Name: chats_attachment chats_attachment_uuid_key; Type: CONSTRAINT; Schema: public; Owner: clokwise
--

ALTER TABLE ONLY public.chats_attachment
    ADD CONSTRAINT chats_attachment_uuid_key UNIQUE (uuid);


--
-- Name: chats_chat_confirmations chats_chat_confirmations_chat_id_user_id_c603f25f_uniq; Type: CONSTRAINT; Schema: public; Owner: clokwise
--

ALTER TABLE ONLY public.chats_chat_confirmations
    ADD CONSTRAINT chats_chat_confirmations_chat_id_user_id_c603f25f_uniq UNIQUE (chat_id, user_id);


--
-- Name: chats_chat_confirmations chats_chat_confirmations_pkey; Type: CONSTRAINT; Schema: public; Owner: clokwise
--

ALTER TABLE ONLY public.chats_chat_confirmations
    ADD CONSTRAINT chats_chat_confirmations_pkey PRIMARY KEY (id);


--
-- Name: chats_chat_participants chats_chat_participants_chat_id_user_id_7a9db70c_uniq; Type: CONSTRAINT; Schema: public; Owner: clokwise
--

ALTER TABLE ONLY public.chats_chat_participants
    ADD CONSTRAINT chats_chat_participants_chat_id_user_id_7a9db70c_uniq UNIQUE (chat_id, user_id);


--
-- Name: chats_chat_participants chats_chat_participants_pkey; Type: CONSTRAINT; Schema: public; Owner: clokwise
--

ALTER TABLE ONLY public.chats_chat_participants
    ADD CONSTRAINT chats_chat_participants_pkey PRIMARY KEY (id);


--
-- Name: chats_chat chats_chat_pkey; Type: CONSTRAINT; Schema: public; Owner: clokwise
--

ALTER TABLE ONLY public.chats_chat
    ADD CONSTRAINT chats_chat_pkey PRIMARY KEY (id);


--
-- Name: chats_message_attachments chats_message_attachment_message_id_attachment_id_6dacd601_uniq; Type: CONSTRAINT; Schema: public; Owner: clokwise
--

ALTER TABLE ONLY public.chats_message_attachments
    ADD CONSTRAINT chats_message_attachment_message_id_attachment_id_6dacd601_uniq UNIQUE (message_id, attachment_id);


--
-- Name: chats_message_attachments chats_message_attachments_pkey; Type: CONSTRAINT; Schema: public; Owner: clokwise
--

ALTER TABLE ONLY public.chats_message_attachments
    ADD CONSTRAINT chats_message_attachments_pkey PRIMARY KEY (id);


--
-- Name: chats_message chats_message_pkey; Type: CONSTRAINT; Schema: public; Owner: clokwise
--

ALTER TABLE ONLY public.chats_message
    ADD CONSTRAINT chats_message_pkey PRIMARY KEY (id);


--
-- Name: chats_messagereadtime chats_messagereadtime_message_id_user_id_1681ede4_uniq; Type: CONSTRAINT; Schema: public; Owner: clokwise
--

ALTER TABLE ONLY public.chats_messagereadtime
    ADD CONSTRAINT chats_messagereadtime_message_id_user_id_1681ede4_uniq UNIQUE (message_id, user_id);


--
-- Name: chats_messagereadtime chats_messagereadtime_pkey; Type: CONSTRAINT; Schema: public; Owner: clokwise
--

ALTER TABLE ONLY public.chats_messagereadtime
    ADD CONSTRAINT chats_messagereadtime_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: clokwise
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: clokwise
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: clokwise
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: clokwise
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: clokwise
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: drf_attachments_attachment drf_attachments_attachment_pkey; Type: CONSTRAINT; Schema: public; Owner: clokwise
--

ALTER TABLE ONLY public.drf_attachments_attachment
    ADD CONSTRAINT drf_attachments_attachment_pkey PRIMARY KEY (id);


--
-- Name: fcm_django_fcmdevice fcm_django_fcmdevice_pkey; Type: CONSTRAINT; Schema: public; Owner: clokwise
--

ALTER TABLE ONLY public.fcm_django_fcmdevice
    ADD CONSTRAINT fcm_django_fcmdevice_pkey PRIMARY KEY (id);


--
-- Name: fcm_django_fcmdevice fcm_django_fcmdevice_registration_id_9918b353_uniq; Type: CONSTRAINT; Schema: public; Owner: clokwise
--

ALTER TABLE ONLY public.fcm_django_fcmdevice
    ADD CONSTRAINT fcm_django_fcmdevice_registration_id_9918b353_uniq UNIQUE (registration_id);


--
-- Name: users_confirmationcode users_confirmationcode_pkey; Type: CONSTRAINT; Schema: public; Owner: clokwise
--

ALTER TABLE ONLY public.users_confirmationcode
    ADD CONSTRAINT users_confirmationcode_pkey PRIMARY KEY (id);


--
-- Name: users_educationdegree users_educationdegree_pkey; Type: CONSTRAINT; Schema: public; Owner: clokwise
--

ALTER TABLE ONLY public.users_educationdegree
    ADD CONSTRAINT users_educationdegree_pkey PRIMARY KEY (id);


--
-- Name: users_educationlevel users_educationlevel_pkey; Type: CONSTRAINT; Schema: public; Owner: clokwise
--

ALTER TABLE ONLY public.users_educationlevel
    ADD CONSTRAINT users_educationlevel_pkey PRIMARY KEY (id);


--
-- Name: users_experienceclassificator users_experienceclassificator_pkey; Type: CONSTRAINT; Schema: public; Owner: clokwise
--

ALTER TABLE ONLY public.users_experienceclassificator
    ADD CONSTRAINT users_experienceclassificator_pkey PRIMARY KEY (id);


--
-- Name: users_experteducationrecord users_experteducationrecord_pkey; Type: CONSTRAINT; Schema: public; Owner: clokwise
--

ALTER TABLE ONLY public.users_experteducationrecord
    ADD CONSTRAINT users_experteducationrecord_pkey PRIMARY KEY (id);


--
-- Name: users_expertexperiencerecord users_expertexperiencerecord_pkey; Type: CONSTRAINT; Schema: public; Owner: clokwise
--

ALTER TABLE ONLY public.users_expertexperiencerecord
    ADD CONSTRAINT users_expertexperiencerecord_pkey PRIMARY KEY (id);


--
-- Name: users_expertexperiencesegment users_expertexperiencesegment_pkey; Type: CONSTRAINT; Schema: public; Owner: clokwise
--

ALTER TABLE ONLY public.users_expertexperiencesegment
    ADD CONSTRAINT users_expertexperiencesegment_pkey PRIMARY KEY (id);


--
-- Name: users_expertsearchrequest users_expertsearchrequest_pkey; Type: CONSTRAINT; Schema: public; Owner: clokwise
--

ALTER TABLE ONLY public.users_expertsearchrequest
    ADD CONSTRAINT users_expertsearchrequest_pkey PRIMARY KEY (id);


--
-- Name: users_expertsearchrequestexpertapplication users_expertsearchrequestexpertapplication_pkey; Type: CONSTRAINT; Schema: public; Owner: clokwise
--

ALTER TABLE ONLY public.users_expertsearchrequestexpertapplication
    ADD CONSTRAINT users_expertsearchrequestexpertapplication_pkey PRIMARY KEY (id);


--
-- Name: users_notification users_notification_pkey; Type: CONSTRAINT; Schema: public; Owner: clokwise
--

ALTER TABLE ONLY public.users_notification
    ADD CONSTRAINT users_notification_pkey PRIMARY KEY (id);


--
-- Name: users_user users_user_email_key; Type: CONSTRAINT; Schema: public; Owner: clokwise
--

ALTER TABLE ONLY public.users_user
    ADD CONSTRAINT users_user_email_key UNIQUE (email);


--
-- Name: users_user_groups users_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: clokwise
--

ALTER TABLE ONLY public.users_user_groups
    ADD CONSTRAINT users_user_groups_pkey PRIMARY KEY (id);


--
-- Name: users_user_groups users_user_groups_user_id_group_id_b88eab82_uniq; Type: CONSTRAINT; Schema: public; Owner: clokwise
--

ALTER TABLE ONLY public.users_user_groups
    ADD CONSTRAINT users_user_groups_user_id_group_id_b88eab82_uniq UNIQUE (user_id, group_id);


--
-- Name: users_user_paid_users_for_view users_user_paid_users_fo_from_user_id_to_user_id_dcf06038_uniq; Type: CONSTRAINT; Schema: public; Owner: clokwise
--

ALTER TABLE ONLY public.users_user_paid_users_for_view
    ADD CONSTRAINT users_user_paid_users_fo_from_user_id_to_user_id_dcf06038_uniq UNIQUE (from_user_id, to_user_id);


--
-- Name: users_user_paid_users_for_view users_user_paid_users_for_view_pkey; Type: CONSTRAINT; Schema: public; Owner: clokwise
--

ALTER TABLE ONLY public.users_user_paid_users_for_view
    ADD CONSTRAINT users_user_paid_users_for_view_pkey PRIMARY KEY (id);


--
-- Name: users_user users_user_pkey; Type: CONSTRAINT; Schema: public; Owner: clokwise
--

ALTER TABLE ONLY public.users_user
    ADD CONSTRAINT users_user_pkey PRIMARY KEY (id);


--
-- Name: users_user_user_permissions users_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: clokwise
--

ALTER TABLE ONLY public.users_user_user_permissions
    ADD CONSTRAINT users_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: users_user_user_permissions users_user_user_permissions_user_id_permission_id_43338c45_uniq; Type: CONSTRAINT; Schema: public; Owner: clokwise
--

ALTER TABLE ONLY public.users_user_user_permissions
    ADD CONSTRAINT users_user_user_permissions_user_id_permission_id_43338c45_uniq UNIQUE (user_id, permission_id);


--
-- Name: users_useravatar users_useravatar_pkey; Type: CONSTRAINT; Schema: public; Owner: clokwise
--

ALTER TABLE ONLY public.users_useravatar
    ADD CONSTRAINT users_useravatar_pkey PRIMARY KEY (id);


--
-- Name: users_userreview users_userreview_pkey; Type: CONSTRAINT; Schema: public; Owner: clokwise
--

ALTER TABLE ONLY public.users_userreview
    ADD CONSTRAINT users_userreview_pkey PRIMARY KEY (id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: clokwise
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: clokwise
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: clokwise
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: clokwise
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: chats_attachment_chat_id_298338fd; Type: INDEX; Schema: public; Owner: clokwise
--

CREATE INDEX chats_attachment_chat_id_298338fd ON public.chats_attachment USING btree (chat_id);


--
-- Name: chats_attachment_creator_id_23aa8d67; Type: INDEX; Schema: public; Owner: clokwise
--

CREATE INDEX chats_attachment_creator_id_23aa8d67 ON public.chats_attachment USING btree (creator_id);


--
-- Name: chats_chat_confirmations_chat_id_725f51c1; Type: INDEX; Schema: public; Owner: clokwise
--

CREATE INDEX chats_chat_confirmations_chat_id_725f51c1 ON public.chats_chat_confirmations USING btree (chat_id);


--
-- Name: chats_chat_confirmations_user_id_f6b4633e; Type: INDEX; Schema: public; Owner: clokwise
--

CREATE INDEX chats_chat_confirmations_user_id_f6b4633e ON public.chats_chat_confirmations USING btree (user_id);


--
-- Name: chats_chat_expert_id_4a56cc42; Type: INDEX; Schema: public; Owner: clokwise
--

CREATE INDEX chats_chat_expert_id_4a56cc42 ON public.chats_chat USING btree (expert_id);


--
-- Name: chats_chat_initiator_id_d1def292; Type: INDEX; Schema: public; Owner: clokwise
--

CREATE INDEX chats_chat_initiator_id_d1def292 ON public.chats_chat USING btree (initiator_id);


--
-- Name: chats_chat_participants_chat_id_c96db030; Type: INDEX; Schema: public; Owner: clokwise
--

CREATE INDEX chats_chat_participants_chat_id_c96db030 ON public.chats_chat_participants USING btree (chat_id);


--
-- Name: chats_chat_participants_user_id_813628c3; Type: INDEX; Schema: public; Owner: clokwise
--

CREATE INDEX chats_chat_participants_user_id_813628c3 ON public.chats_chat_participants USING btree (user_id);


--
-- Name: chats_chat_search_request_id_38fb6a5d; Type: INDEX; Schema: public; Owner: clokwise
--

CREATE INDEX chats_chat_search_request_id_38fb6a5d ON public.chats_chat USING btree (search_request_id);


--
-- Name: chats_message_attachments_attachment_id_aa596e0c; Type: INDEX; Schema: public; Owner: clokwise
--

CREATE INDEX chats_message_attachments_attachment_id_aa596e0c ON public.chats_message_attachments USING btree (attachment_id);


--
-- Name: chats_message_attachments_message_id_014ec2dd; Type: INDEX; Schema: public; Owner: clokwise
--

CREATE INDEX chats_message_attachments_message_id_014ec2dd ON public.chats_message_attachments USING btree (message_id);


--
-- Name: chats_message_chat_id_f3080004; Type: INDEX; Schema: public; Owner: clokwise
--

CREATE INDEX chats_message_chat_id_f3080004 ON public.chats_message USING btree (chat_id);


--
-- Name: chats_message_from_user_id_6923d6be; Type: INDEX; Schema: public; Owner: clokwise
--

CREATE INDEX chats_message_from_user_id_6923d6be ON public.chats_message USING btree (from_user_id);


--
-- Name: chats_messagereadtime_message_id_91b4b1a4; Type: INDEX; Schema: public; Owner: clokwise
--

CREATE INDEX chats_messagereadtime_message_id_91b4b1a4 ON public.chats_messagereadtime USING btree (message_id);


--
-- Name: chats_messagereadtime_user_id_deea17f3; Type: INDEX; Schema: public; Owner: clokwise
--

CREATE INDEX chats_messagereadtime_user_id_deea17f3 ON public.chats_messagereadtime USING btree (user_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: clokwise
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: clokwise
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: clokwise
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: clokwise
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: drf_attachments_attachment_content_type_id_a3d664de; Type: INDEX; Schema: public; Owner: clokwise
--

CREATE INDEX drf_attachments_attachment_content_type_id_a3d664de ON public.drf_attachments_attachment USING btree (content_type_id);


--
-- Name: drf_attachments_attachment_object_id_750ca08a; Type: INDEX; Schema: public; Owner: clokwise
--

CREATE INDEX drf_attachments_attachment_object_id_750ca08a ON public.drf_attachments_attachment USING btree (object_id);


--
-- Name: drf_attachments_attachment_object_id_750ca08a_like; Type: INDEX; Schema: public; Owner: clokwise
--

CREATE INDEX drf_attachments_attachment_object_id_750ca08a_like ON public.drf_attachments_attachment USING btree (object_id varchar_pattern_ops);


--
-- Name: fcm_django__registr_dacdb2_idx; Type: INDEX; Schema: public; Owner: clokwise
--

CREATE INDEX fcm_django__registr_dacdb2_idx ON public.fcm_django_fcmdevice USING btree (registration_id, user_id);


--
-- Name: fcm_django_fcmdevice_device_id_a9406c36; Type: INDEX; Schema: public; Owner: clokwise
--

CREATE INDEX fcm_django_fcmdevice_device_id_a9406c36 ON public.fcm_django_fcmdevice USING btree (device_id);


--
-- Name: fcm_django_fcmdevice_registration_id_9918b353_like; Type: INDEX; Schema: public; Owner: clokwise
--

CREATE INDEX fcm_django_fcmdevice_registration_id_9918b353_like ON public.fcm_django_fcmdevice USING btree (registration_id text_pattern_ops);


--
-- Name: fcm_django_fcmdevice_user_id_6cdfc0a2; Type: INDEX; Schema: public; Owner: clokwise
--

CREATE INDEX fcm_django_fcmdevice_user_id_6cdfc0a2 ON public.fcm_django_fcmdevice USING btree (user_id);


--
-- Name: users_confirmationcode_user_id_b81fc006; Type: INDEX; Schema: public; Owner: clokwise
--

CREATE INDEX users_confirmationcode_user_id_b81fc006 ON public.users_confirmationcode USING btree (user_id);


--
-- Name: users_experienceclassificator_parent_id_b41b6b58; Type: INDEX; Schema: public; Owner: clokwise
--

CREATE INDEX users_experienceclassificator_parent_id_b41b6b58 ON public.users_experienceclassificator USING btree (parent_id);


--
-- Name: users_experteducationrecord_education_degree_id_405f9931; Type: INDEX; Schema: public; Owner: clokwise
--

CREATE INDEX users_experteducationrecord_education_degree_id_405f9931 ON public.users_experteducationrecord USING btree (education_degree_id);


--
-- Name: users_experteducationrecord_education_level_id_963d6caa; Type: INDEX; Schema: public; Owner: clokwise
--

CREATE INDEX users_experteducationrecord_education_level_id_963d6caa ON public.users_experteducationrecord USING btree (education_level_id);


--
-- Name: users_experteducationrecord_user_id_9721ff3f; Type: INDEX; Schema: public; Owner: clokwise
--

CREATE INDEX users_experteducationrecord_user_id_9721ff3f ON public.users_experteducationrecord USING btree (user_id);


--
-- Name: users_expertexperiencerecord_user_id_62d0ec2a; Type: INDEX; Schema: public; Owner: clokwise
--

CREATE INDEX users_expertexperiencerecord_user_id_62d0ec2a ON public.users_expertexperiencerecord USING btree (user_id);


--
-- Name: users_expertexperiencesegment_experience_record_id_e689660c; Type: INDEX; Schema: public; Owner: clokwise
--

CREATE INDEX users_expertexperiencesegment_experience_record_id_e689660c ON public.users_expertexperiencesegment USING btree (experience_record_id);


--
-- Name: users_expertexperiencesegment_function_id_6dbfced9; Type: INDEX; Schema: public; Owner: clokwise
--

CREATE INDEX users_expertexperiencesegment_function_id_6dbfced9 ON public.users_expertexperiencesegment USING btree (function_id);


--
-- Name: users_expertexperiencesegment_industry_id_c07b954c; Type: INDEX; Schema: public; Owner: clokwise
--

CREATE INDEX users_expertexperiencesegment_industry_id_c07b954c ON public.users_expertexperiencesegment USING btree (industry_id);


--
-- Name: users_expertexperiencesegment_subfunction_id_b255e9f8; Type: INDEX; Schema: public; Owner: clokwise
--

CREATE INDEX users_expertexperiencesegment_subfunction_id_b255e9f8 ON public.users_expertexperiencesegment USING btree (subfunction_id);


--
-- Name: users_expertexperiencesegment_subindustry_id_dfc14573; Type: INDEX; Schema: public; Owner: clokwise
--

CREATE INDEX users_expertexperiencesegment_subindustry_id_dfc14573 ON public.users_expertexperiencesegment USING btree (subindustry_id);


--
-- Name: users_expertsearchrequest_creator_id_abd4d753; Type: INDEX; Schema: public; Owner: clokwise
--

CREATE INDEX users_expertsearchrequest_creator_id_abd4d753 ON public.users_expertsearchrequest USING btree (creator_id);


--
-- Name: users_expertsearchrequest_function_id_11cfb0aa; Type: INDEX; Schema: public; Owner: clokwise
--

CREATE INDEX users_expertsearchrequest_function_id_11cfb0aa ON public.users_expertsearchrequest USING btree (function_id);


--
-- Name: users_expertsearchrequest_industry_id_da908395; Type: INDEX; Schema: public; Owner: clokwise
--

CREATE INDEX users_expertsearchrequest_industry_id_da908395 ON public.users_expertsearchrequest USING btree (industry_id);


--
-- Name: users_expertsearchrequest_subfunction_id_c57486a2; Type: INDEX; Schema: public; Owner: clokwise
--

CREATE INDEX users_expertsearchrequest_subfunction_id_c57486a2 ON public.users_expertsearchrequest USING btree (subfunction_id);


--
-- Name: users_expertsearchrequest_subindustry_id_fd609dc3; Type: INDEX; Schema: public; Owner: clokwise
--

CREATE INDEX users_expertsearchrequest_subindustry_id_fd609dc3 ON public.users_expertsearchrequest USING btree (subindustry_id);


--
-- Name: users_expertsearchrequestexpertapplication_expert_id_ba4e192f; Type: INDEX; Schema: public; Owner: clokwise
--

CREATE INDEX users_expertsearchrequestexpertapplication_expert_id_ba4e192f ON public.users_expertsearchrequestexpertapplication USING btree (expert_id);


--
-- Name: users_expertsearchrequestexpertapplication_request_id_942c593b; Type: INDEX; Schema: public; Owner: clokwise
--

CREATE INDEX users_expertsearchrequestexpertapplication_request_id_942c593b ON public.users_expertsearchrequestexpertapplication USING btree (request_id);


--
-- Name: users_notification_receiver_id_40c65125; Type: INDEX; Schema: public; Owner: clokwise
--

CREATE INDEX users_notification_receiver_id_40c65125 ON public.users_notification USING btree (receiver_id);


--
-- Name: users_notification_sender_id_d487ebb3; Type: INDEX; Schema: public; Owner: clokwise
--

CREATE INDEX users_notification_sender_id_d487ebb3 ON public.users_notification USING btree (sender_id);


--
-- Name: users_user_avatar_id_2054405b; Type: INDEX; Schema: public; Owner: clokwise
--

CREATE INDEX users_user_avatar_id_2054405b ON public.users_user USING btree (avatar_id);


--
-- Name: users_user_email_243f6e77_like; Type: INDEX; Schema: public; Owner: clokwise
--

CREATE INDEX users_user_email_243f6e77_like ON public.users_user USING btree (email varchar_pattern_ops);


--
-- Name: users_user_groups_group_id_9afc8d0e; Type: INDEX; Schema: public; Owner: clokwise
--

CREATE INDEX users_user_groups_group_id_9afc8d0e ON public.users_user_groups USING btree (group_id);


--
-- Name: users_user_groups_user_id_5f6f5a90; Type: INDEX; Schema: public; Owner: clokwise
--

CREATE INDEX users_user_groups_user_id_5f6f5a90 ON public.users_user_groups USING btree (user_id);


--
-- Name: users_user_paid_users_for_view_from_user_id_e8b93bc5; Type: INDEX; Schema: public; Owner: clokwise
--

CREATE INDEX users_user_paid_users_for_view_from_user_id_e8b93bc5 ON public.users_user_paid_users_for_view USING btree (from_user_id);


--
-- Name: users_user_paid_users_for_view_to_user_id_b0aba243; Type: INDEX; Schema: public; Owner: clokwise
--

CREATE INDEX users_user_paid_users_for_view_to_user_id_b0aba243 ON public.users_user_paid_users_for_view USING btree (to_user_id);


--
-- Name: users_user_user_permissions_permission_id_0b93982e; Type: INDEX; Schema: public; Owner: clokwise
--

CREATE INDEX users_user_user_permissions_permission_id_0b93982e ON public.users_user_user_permissions USING btree (permission_id);


--
-- Name: users_user_user_permissions_user_id_20aca447; Type: INDEX; Schema: public; Owner: clokwise
--

CREATE INDEX users_user_user_permissions_user_id_20aca447 ON public.users_user_user_permissions USING btree (user_id);


--
-- Name: users_userreview_chat_id_16549239; Type: INDEX; Schema: public; Owner: clokwise
--

CREATE INDEX users_userreview_chat_id_16549239 ON public.users_userreview USING btree (chat_id);


--
-- Name: users_userreview_reviewer_id_a95bfc89; Type: INDEX; Schema: public; Owner: clokwise
--

CREATE INDEX users_userreview_reviewer_id_a95bfc89 ON public.users_userreview USING btree (reviewer_id);


--
-- Name: users_userreview_user_id_31fbea77; Type: INDEX; Schema: public; Owner: clokwise
--

CREATE INDEX users_userreview_user_id_31fbea77 ON public.users_userreview USING btree (user_id);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: clokwise
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: clokwise
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: clokwise
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: chats_attachment chats_attachment_chat_id_298338fd_fk_chats_chat_id; Type: FK CONSTRAINT; Schema: public; Owner: clokwise
--

ALTER TABLE ONLY public.chats_attachment
    ADD CONSTRAINT chats_attachment_chat_id_298338fd_fk_chats_chat_id FOREIGN KEY (chat_id) REFERENCES public.chats_chat(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: chats_attachment chats_attachment_creator_id_23aa8d67_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: clokwise
--

ALTER TABLE ONLY public.chats_attachment
    ADD CONSTRAINT chats_attachment_creator_id_23aa8d67_fk_users_user_id FOREIGN KEY (creator_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: chats_chat_confirmations chats_chat_confirmations_chat_id_725f51c1_fk_chats_chat_id; Type: FK CONSTRAINT; Schema: public; Owner: clokwise
--

ALTER TABLE ONLY public.chats_chat_confirmations
    ADD CONSTRAINT chats_chat_confirmations_chat_id_725f51c1_fk_chats_chat_id FOREIGN KEY (chat_id) REFERENCES public.chats_chat(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: chats_chat_confirmations chats_chat_confirmations_user_id_f6b4633e_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: clokwise
--

ALTER TABLE ONLY public.chats_chat_confirmations
    ADD CONSTRAINT chats_chat_confirmations_user_id_f6b4633e_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: chats_chat chats_chat_expert_id_4a56cc42_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: clokwise
--

ALTER TABLE ONLY public.chats_chat
    ADD CONSTRAINT chats_chat_expert_id_4a56cc42_fk_users_user_id FOREIGN KEY (expert_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: chats_chat chats_chat_initiator_id_d1def292_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: clokwise
--

ALTER TABLE ONLY public.chats_chat
    ADD CONSTRAINT chats_chat_initiator_id_d1def292_fk_users_user_id FOREIGN KEY (initiator_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: chats_chat_participants chats_chat_participants_chat_id_c96db030_fk_chats_chat_id; Type: FK CONSTRAINT; Schema: public; Owner: clokwise
--

ALTER TABLE ONLY public.chats_chat_participants
    ADD CONSTRAINT chats_chat_participants_chat_id_c96db030_fk_chats_chat_id FOREIGN KEY (chat_id) REFERENCES public.chats_chat(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: chats_chat_participants chats_chat_participants_user_id_813628c3_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: clokwise
--

ALTER TABLE ONLY public.chats_chat_participants
    ADD CONSTRAINT chats_chat_participants_user_id_813628c3_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: chats_chat chats_chat_search_request_id_38fb6a5d_fk_users_exp; Type: FK CONSTRAINT; Schema: public; Owner: clokwise
--

ALTER TABLE ONLY public.chats_chat
    ADD CONSTRAINT chats_chat_search_request_id_38fb6a5d_fk_users_exp FOREIGN KEY (search_request_id) REFERENCES public.users_expertsearchrequest(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: chats_message_attachments chats_message_attach_attachment_id_aa596e0c_fk_chats_att; Type: FK CONSTRAINT; Schema: public; Owner: clokwise
--

ALTER TABLE ONLY public.chats_message_attachments
    ADD CONSTRAINT chats_message_attach_attachment_id_aa596e0c_fk_chats_att FOREIGN KEY (attachment_id) REFERENCES public.chats_attachment(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: chats_message_attachments chats_message_attach_message_id_014ec2dd_fk_chats_mes; Type: FK CONSTRAINT; Schema: public; Owner: clokwise
--

ALTER TABLE ONLY public.chats_message_attachments
    ADD CONSTRAINT chats_message_attach_message_id_014ec2dd_fk_chats_mes FOREIGN KEY (message_id) REFERENCES public.chats_message(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: chats_message chats_message_chat_id_f3080004_fk_chats_chat_id; Type: FK CONSTRAINT; Schema: public; Owner: clokwise
--

ALTER TABLE ONLY public.chats_message
    ADD CONSTRAINT chats_message_chat_id_f3080004_fk_chats_chat_id FOREIGN KEY (chat_id) REFERENCES public.chats_chat(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: chats_message chats_message_from_user_id_6923d6be_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: clokwise
--

ALTER TABLE ONLY public.chats_message
    ADD CONSTRAINT chats_message_from_user_id_6923d6be_fk_users_user_id FOREIGN KEY (from_user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: chats_messagereadtime chats_messagereadtime_message_id_91b4b1a4_fk_chats_message_id; Type: FK CONSTRAINT; Schema: public; Owner: clokwise
--

ALTER TABLE ONLY public.chats_messagereadtime
    ADD CONSTRAINT chats_messagereadtime_message_id_91b4b1a4_fk_chats_message_id FOREIGN KEY (message_id) REFERENCES public.chats_message(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: chats_messagereadtime chats_messagereadtime_user_id_deea17f3_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: clokwise
--

ALTER TABLE ONLY public.chats_messagereadtime
    ADD CONSTRAINT chats_messagereadtime_user_id_deea17f3_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: clokwise
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: clokwise
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: drf_attachments_attachment drf_attachments_atta_content_type_id_a3d664de_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: clokwise
--

ALTER TABLE ONLY public.drf_attachments_attachment
    ADD CONSTRAINT drf_attachments_atta_content_type_id_a3d664de_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: fcm_django_fcmdevice fcm_django_fcmdevice_user_id_6cdfc0a2_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: clokwise
--

ALTER TABLE ONLY public.fcm_django_fcmdevice
    ADD CONSTRAINT fcm_django_fcmdevice_user_id_6cdfc0a2_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_confirmationcode users_confirmationcode_user_id_b81fc006_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: clokwise
--

ALTER TABLE ONLY public.users_confirmationcode
    ADD CONSTRAINT users_confirmationcode_user_id_b81fc006_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_experienceclassificator users_experienceclas_parent_id_b41b6b58_fk_users_exp; Type: FK CONSTRAINT; Schema: public; Owner: clokwise
--

ALTER TABLE ONLY public.users_experienceclassificator
    ADD CONSTRAINT users_experienceclas_parent_id_b41b6b58_fk_users_exp FOREIGN KEY (parent_id) REFERENCES public.users_experienceclassificator(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_experteducationrecord users_experteducatio_education_degree_id_405f9931_fk_users_edu; Type: FK CONSTRAINT; Schema: public; Owner: clokwise
--

ALTER TABLE ONLY public.users_experteducationrecord
    ADD CONSTRAINT users_experteducatio_education_degree_id_405f9931_fk_users_edu FOREIGN KEY (education_degree_id) REFERENCES public.users_educationdegree(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_experteducationrecord users_experteducatio_education_level_id_963d6caa_fk_users_edu; Type: FK CONSTRAINT; Schema: public; Owner: clokwise
--

ALTER TABLE ONLY public.users_experteducationrecord
    ADD CONSTRAINT users_experteducatio_education_level_id_963d6caa_fk_users_edu FOREIGN KEY (education_level_id) REFERENCES public.users_educationlevel(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_experteducationrecord users_experteducationrecord_user_id_9721ff3f_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: clokwise
--

ALTER TABLE ONLY public.users_experteducationrecord
    ADD CONSTRAINT users_experteducationrecord_user_id_9721ff3f_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_expertexperiencesegment users_expertexperien_experience_record_id_e689660c_fk_users_exp; Type: FK CONSTRAINT; Schema: public; Owner: clokwise
--

ALTER TABLE ONLY public.users_expertexperiencesegment
    ADD CONSTRAINT users_expertexperien_experience_record_id_e689660c_fk_users_exp FOREIGN KEY (experience_record_id) REFERENCES public.users_expertexperiencerecord(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_expertexperiencesegment users_expertexperien_function_id_6dbfced9_fk_users_exp; Type: FK CONSTRAINT; Schema: public; Owner: clokwise
--

ALTER TABLE ONLY public.users_expertexperiencesegment
    ADD CONSTRAINT users_expertexperien_function_id_6dbfced9_fk_users_exp FOREIGN KEY (function_id) REFERENCES public.users_experienceclassificator(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_expertexperiencesegment users_expertexperien_industry_id_c07b954c_fk_users_exp; Type: FK CONSTRAINT; Schema: public; Owner: clokwise
--

ALTER TABLE ONLY public.users_expertexperiencesegment
    ADD CONSTRAINT users_expertexperien_industry_id_c07b954c_fk_users_exp FOREIGN KEY (industry_id) REFERENCES public.users_experienceclassificator(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_expertexperiencesegment users_expertexperien_subfunction_id_b255e9f8_fk_users_exp; Type: FK CONSTRAINT; Schema: public; Owner: clokwise
--

ALTER TABLE ONLY public.users_expertexperiencesegment
    ADD CONSTRAINT users_expertexperien_subfunction_id_b255e9f8_fk_users_exp FOREIGN KEY (subfunction_id) REFERENCES public.users_experienceclassificator(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_expertexperiencesegment users_expertexperien_subindustry_id_dfc14573_fk_users_exp; Type: FK CONSTRAINT; Schema: public; Owner: clokwise
--

ALTER TABLE ONLY public.users_expertexperiencesegment
    ADD CONSTRAINT users_expertexperien_subindustry_id_dfc14573_fk_users_exp FOREIGN KEY (subindustry_id) REFERENCES public.users_experienceclassificator(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_expertexperiencerecord users_expertexperiencerecord_user_id_62d0ec2a_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: clokwise
--

ALTER TABLE ONLY public.users_expertexperiencerecord
    ADD CONSTRAINT users_expertexperiencerecord_user_id_62d0ec2a_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_expertsearchrequestexpertapplication users_expertsearchre_expert_id_ba4e192f_fk_users_use; Type: FK CONSTRAINT; Schema: public; Owner: clokwise
--

ALTER TABLE ONLY public.users_expertsearchrequestexpertapplication
    ADD CONSTRAINT users_expertsearchre_expert_id_ba4e192f_fk_users_use FOREIGN KEY (expert_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_expertsearchrequest users_expertsearchre_function_id_11cfb0aa_fk_users_exp; Type: FK CONSTRAINT; Schema: public; Owner: clokwise
--

ALTER TABLE ONLY public.users_expertsearchrequest
    ADD CONSTRAINT users_expertsearchre_function_id_11cfb0aa_fk_users_exp FOREIGN KEY (function_id) REFERENCES public.users_experienceclassificator(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_expertsearchrequest users_expertsearchre_industry_id_da908395_fk_users_exp; Type: FK CONSTRAINT; Schema: public; Owner: clokwise
--

ALTER TABLE ONLY public.users_expertsearchrequest
    ADD CONSTRAINT users_expertsearchre_industry_id_da908395_fk_users_exp FOREIGN KEY (industry_id) REFERENCES public.users_experienceclassificator(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_expertsearchrequestexpertapplication users_expertsearchre_request_id_942c593b_fk_users_exp; Type: FK CONSTRAINT; Schema: public; Owner: clokwise
--

ALTER TABLE ONLY public.users_expertsearchrequestexpertapplication
    ADD CONSTRAINT users_expertsearchre_request_id_942c593b_fk_users_exp FOREIGN KEY (request_id) REFERENCES public.users_expertsearchrequest(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_expertsearchrequest users_expertsearchre_subfunction_id_c57486a2_fk_users_exp; Type: FK CONSTRAINT; Schema: public; Owner: clokwise
--

ALTER TABLE ONLY public.users_expertsearchrequest
    ADD CONSTRAINT users_expertsearchre_subfunction_id_c57486a2_fk_users_exp FOREIGN KEY (subfunction_id) REFERENCES public.users_experienceclassificator(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_expertsearchrequest users_expertsearchre_subindustry_id_fd609dc3_fk_users_exp; Type: FK CONSTRAINT; Schema: public; Owner: clokwise
--

ALTER TABLE ONLY public.users_expertsearchrequest
    ADD CONSTRAINT users_expertsearchre_subindustry_id_fd609dc3_fk_users_exp FOREIGN KEY (subindustry_id) REFERENCES public.users_experienceclassificator(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_expertsearchrequest users_expertsearchrequest_creator_id_abd4d753_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: clokwise
--

ALTER TABLE ONLY public.users_expertsearchrequest
    ADD CONSTRAINT users_expertsearchrequest_creator_id_abd4d753_fk_users_user_id FOREIGN KEY (creator_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_notification users_notification_receiver_id_40c65125_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: clokwise
--

ALTER TABLE ONLY public.users_notification
    ADD CONSTRAINT users_notification_receiver_id_40c65125_fk_users_user_id FOREIGN KEY (receiver_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_notification users_notification_sender_id_d487ebb3_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: clokwise
--

ALTER TABLE ONLY public.users_notification
    ADD CONSTRAINT users_notification_sender_id_d487ebb3_fk_users_user_id FOREIGN KEY (sender_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user users_user_avatar_id_2054405b_fk_users_useravatar_id; Type: FK CONSTRAINT; Schema: public; Owner: clokwise
--

ALTER TABLE ONLY public.users_user
    ADD CONSTRAINT users_user_avatar_id_2054405b_fk_users_useravatar_id FOREIGN KEY (avatar_id) REFERENCES public.users_useravatar(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_groups users_user_groups_group_id_9afc8d0e_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: clokwise
--

ALTER TABLE ONLY public.users_user_groups
    ADD CONSTRAINT users_user_groups_group_id_9afc8d0e_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_groups users_user_groups_user_id_5f6f5a90_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: clokwise
--

ALTER TABLE ONLY public.users_user_groups
    ADD CONSTRAINT users_user_groups_user_id_5f6f5a90_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_paid_users_for_view users_user_paid_user_from_user_id_e8b93bc5_fk_users_use; Type: FK CONSTRAINT; Schema: public; Owner: clokwise
--

ALTER TABLE ONLY public.users_user_paid_users_for_view
    ADD CONSTRAINT users_user_paid_user_from_user_id_e8b93bc5_fk_users_use FOREIGN KEY (from_user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_paid_users_for_view users_user_paid_user_to_user_id_b0aba243_fk_users_use; Type: FK CONSTRAINT; Schema: public; Owner: clokwise
--

ALTER TABLE ONLY public.users_user_paid_users_for_view
    ADD CONSTRAINT users_user_paid_user_to_user_id_b0aba243_fk_users_use FOREIGN KEY (to_user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_user_permissions users_user_user_perm_permission_id_0b93982e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: clokwise
--

ALTER TABLE ONLY public.users_user_user_permissions
    ADD CONSTRAINT users_user_user_perm_permission_id_0b93982e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_user_permissions users_user_user_permissions_user_id_20aca447_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: clokwise
--

ALTER TABLE ONLY public.users_user_user_permissions
    ADD CONSTRAINT users_user_user_permissions_user_id_20aca447_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_userreview users_userreview_chat_id_16549239_fk_chats_chat_id; Type: FK CONSTRAINT; Schema: public; Owner: clokwise
--

ALTER TABLE ONLY public.users_userreview
    ADD CONSTRAINT users_userreview_chat_id_16549239_fk_chats_chat_id FOREIGN KEY (chat_id) REFERENCES public.chats_chat(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_userreview users_userreview_reviewer_id_a95bfc89_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: clokwise
--

ALTER TABLE ONLY public.users_userreview
    ADD CONSTRAINT users_userreview_reviewer_id_a95bfc89_fk_users_user_id FOREIGN KEY (reviewer_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_userreview users_userreview_user_id_31fbea77_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: clokwise
--

ALTER TABLE ONLY public.users_userreview
    ADD CONSTRAINT users_userreview_user_id_31fbea77_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: pg_database_owner
--

GRANT ALL ON SCHEMA public TO clokwise;


--
-- PostgreSQL database dump complete
--

