# Generated by Django 5.1 on 2024-08-28 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertexperiencesegment',
            name='experience_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='users.expertexperiencerecord'),
        ),
    ]
