# Generated by Django 5.1 on 2024-08-29 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_expertexperiencesegment_experience_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='experteducationrecord',
            name='department_name',
            field=models.CharField(default='blank', max_length=256, verbose_name='Кафедра'),
            preserve_default=False,
        ),
    ]
