# Generated by Django 5.1 on 2024-08-30 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_experteducationrecord_department_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company_description',
            field=models.CharField(blank=True, max_length=4096, null=True, verbose_name='Описание компании'),
        ),
        migrations.AddField(
            model_name='user',
            name='company_inn',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ИНН'),
        ),
        migrations.AddField(
            model_name='user',
            name='company_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Название компании'),
        ),
        migrations.AddField(
            model_name='user',
            name='company_website',
            field=models.URLField(blank=True, null=True, verbose_name='Сайт компании'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_legal_entity',
            field=models.BooleanField(default=False, verbose_name='Юридическое лицо'),
        ),
        migrations.AddField(
            model_name='user',
            name='person_activity_description',
            field=models.CharField(blank=True, max_length=4096, null=True, verbose_name='Описание деятельности'),
        ),
        migrations.AddField(
            model_name='user',
            name='person_website',
            field=models.URLField(blank=True, null=True, verbose_name='Персональный сайт'),
        ),
    ]
