# Generated by Django 5.1 on 2024-09-04 00:17

import django.db.models.deletion
import django.utils.timezone
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_useravatar_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resetpasswordtoken',
            name='user',
        ),
        migrations.CreateModel(
            name='ConfirmationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('email', models.EmailField(max_length=254, verbose_name='Адрес электронной почты')),
                ('token', models.CharField(default=users.models.generate_code, max_length=128)),
                ('type', models.CharField(choices=[('RESET_PASSWORD', 'Сброс пароля'), ('CONFIRM_EMAIL', 'Подтверждение почты'), ('UPDATE_PERSONAL_INFORMATION', 'Редактирование основной информации профиля')], max_length=64, verbose_name='Тип')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmation_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Код подтверждения',
                'verbose_name_plural': 'Коды подтверждения',
            },
        ),
        migrations.DeleteModel(
            name='ConfirmEmailToken',
        ),
        migrations.DeleteModel(
            name='ResetPasswordToken',
        ),
    ]
