# Generated by Django 5.1 on 2024-09-04 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_resetpasswordtoken_user_confirmationcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_company_info_verification_requested',
            field=models.BooleanField(blank=True, default=False, verbose_name='Требуется верификация компании'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_company_info_verified',
            field=models.BooleanField(blank=True, default=False, verbose_name='Информация о организации подтверждена'),
        ),
    ]
