# Generated by Django 5.1 on 2024-09-07 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceClassificator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=96, verbose_name='Название')),
                ('type', models.CharField(choices=[('INDUSTRY', 'Отрасль'), ('SUBINDUSTRY', 'Подотрасль'), ('FUNCTION', 'Функция'), ('SUBFUNCTION', 'Подфункция')], max_length=64, verbose_name='Тип')),
                ('order_number', models.PositiveIntegerField(default=0, verbose_name='Порядковый номер')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='users.experienceclassificator', verbose_name='Родительский классификатор')),
            ],
        ),
    ]
