# Generated by Django 5.1 on 2024-09-07 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_experienceclassificator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experienceclassificator',
            options={'verbose_name': 'Классификатор опыта', 'verbose_name_plural': 'Классификаторы опыта'},
        ),
    ]
