# Generated by Django 5.1 on 2024-09-08 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_experienceclassificator_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiencesubfunction',
            name='function',
        ),
        migrations.AlterField(
            model_name='expertexperiencesegment',
            name='function',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='in_segments_as_function', to='users.experienceclassificator'),
        ),
        migrations.RemoveField(
            model_name='experiencesubindustry',
            name='industry',
        ),
        migrations.AlterField(
            model_name='expertexperiencesegment',
            name='industry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='in_segments_as_industry', to='users.experienceclassificator'),
        ),
        migrations.AlterField(
            model_name='expertexperiencesegment',
            name='subfunction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='in_segments_as_subfunction', to='users.experienceclassificator'),
        ),
        migrations.AlterField(
            model_name='expertexperiencesegment',
            name='subindustry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='in_segments_as_subindustry', to='users.experienceclassificator'),
        ),
        migrations.DeleteModel(
            name='ExperienceFunction',
        ),
        migrations.DeleteModel(
            name='ExperienceIndustry',
        ),
        migrations.DeleteModel(
            name='ExperienceSubfunction',
        ),
        migrations.DeleteModel(
            name='ExperienceSubindustry',
        ),
    ]
