# Generated by Django 5.1 on 2024-09-10 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_experiencesubfunction_function_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company_inn',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='ИНН'),
        ),
    ]
