# Generated by Django 5.1 on 2024-09-16 05:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_user_company_inn'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertSearchRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('datetime_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время создания')),
                ('description', models.CharField(blank=True, max_length=4096, null=True, verbose_name='Описание задачи')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Заказчик')),
                ('function', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='function_expert_search_requests', to='users.experienceclassificator')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='industry_expert_search_requests', to='users.experienceclassificator')),
                ('subfunction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subfunction_expert_search_requests', to='users.experienceclassificator')),
                ('subindustry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subindustry_expert_search_requests', to='users.experienceclassificator')),
            ],
            options={
                'verbose_name': 'Общий запрос',
                'verbose_name_plural': 'Общие запросы',
            },
        ),
    ]
