# Generated by Django 5.1 on 2024-09-16 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_expertsearchrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expertexperiencerecord',
            options={'verbose_name': 'Запись опыта эксперта', 'verbose_name_plural': 'Записи опыта эксперта'},
        ),
        migrations.AlterField(
            model_name='expertexperiencesegment',
            name='description',
            field=models.TextField(max_length=4096, verbose_name='Описание опыта'),
        ),
        migrations.AlterField(
            model_name='expertsearchrequest',
            name='description',
            field=models.TextField(blank=True, max_length=4096, null=True, verbose_name='Описание задачи'),
        ),
        migrations.AlterField(
            model_name='user',
            name='company_description',
            field=models.TextField(blank=True, max_length=4096, null=True, verbose_name='Описание компании'),
        ),
        migrations.AlterField(
            model_name='user',
            name='person_activity_description',
            field=models.TextField(blank=True, max_length=4096, null=True, verbose_name='Описание деятельности'),
        ),
    ]
