# Generated by Django 5.1 on 2024-09-18 08:07

import datetime
import django.db.models.expressions
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertsearchrequest',
            name='datetime_expire',
            field=models.DateTimeField(db_default=django.db.models.expressions.CombinedExpression(django.db.models.functions.datetime.Now(), '+', models.Value(datetime.timedelta(days=7))), verbose_name='Время удаления'),
        ),
    ]
