# Generated by Django 5.1 on 2024-09-18 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_expertsearchrequest_datetime_expire'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertsearchrequest',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, verbose_name='Активен'),
        ),
    ]
