# Generated by Django 5.1 on 2024-09-18 12:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_expertsearchrequest_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertSearchRequestExpertApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время создания')),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL, verbose_name='Эксперт')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='users.expertsearchrequest', verbose_name='Запрос')),
            ],
        ),
    ]
