# Generated by Django 5.1 on 2024-09-24 06:47

import django.contrib.postgres.fields.hstore
from django.db import migrations
from django.contrib.postgres.operations import HStoreExtension


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_expertsearchrequestexpertapplication'),
    ]

    operations = [
        HStoreExtension(),
        migrations.AddField(
            model_name='notification',
            name='other_data',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True, verbose_name='Прочие данные'),
        ),
    ]
