# Generated by Django 5.1 on 2024-09-28 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_notification_other_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertsearchrequest',
            name='type',
            field=models.CharField(choices=[('CLOSED', 'Закрытый'), ('PUBLIC', 'Общий')], default='PUBLIC', max_length=64, verbose_name='Тип'),
        ),
    ]
