# Generated by Django 5.1 on 2024-10-10 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0005_message_available_until_message_is_deleted'),
        ('users', '0022_alter_expertsearchrequest_options_userreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreview',
            name='chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='chats.chat'),
        ),
    ]
