# Generated by Django 5.1 on 2024-10-10 14:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_userreview_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreview',
            name='datetime_created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата создания'),
        ),
    ]
