# Generated by Django 5.1 on 2024-10-14 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_userreview_datetime_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='datetime_read',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Время прочтения'),
        ),
    ]
