# Generated by Django 5.1 on 2024-10-14 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_notification_datetime_read'),
    ]

    operations = [
        migrations.RenameField(
            model_name='confirmationcode',
            old_name='date_created',
            new_name='datetime_created',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='date_created',
            new_name='datetime_created',
        ),
    ]
