# Generated by Django 5.1 on 2024-10-25 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_notification_send_firebase_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscription_until',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата окончания подписки'),
        ),
    ]
