# Generated by Django 5.1 on 2024-10-25 16:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_user_subscription_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='paid_users_for_view',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Оплатившие просмотр профиля'),
        ),
    ]
