/// Flutter icons CwIcons
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CwIcons
///      fonts:
///       - asset: fonts/CwIcons.ttf
///
/// 
///
library;
import 'package:flutter/widgets.dart';

class CwIcons {
  CwIcons._();

  static const _kFontFam = 'CwIcons';
  static const String? _kFontPkg = null;

  static const IconData refresh = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
