# Generated by Django 5.1 on 2024-10-04 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='confirmations',
            field=models.ManyToManyField(related_name='confirmed_chats', to=settings.AUTH_USER_MODEL, verbose_name='Подтвердившие диалог'),
        ),
        migrations.AddField(
            model_name='chat',
            name='initiator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='initiated_chats', to=settings.AUTH_USER_MODEL, verbose_name='Инициатор'),
        ),
        migrations.AddField(
            model_name='message',
            name='from_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель'),
            preserve_default=False,
        ),
    ]
