# Generated by Django 5.1 on 2024-10-05 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_chat_confirmations_chat_initiator_message_from_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='is_closed',
            field=models.BooleanField(blank=True, default=False, verbose_name='Завершён'),
        ),
    ]
