# Generated by Django 5.1 on 2024-10-06 15:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_chat_is_closed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.CreateModel(
            name='MessageReadTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_read', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата прочтения')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_times', to='chats.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_read_times', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Время прочтения сообщения',
                'verbose_name_plural': 'Время прочтения сообщений',
                'unique_together': {('message', 'user')},
            },
        ),
    ]
