# Generated by Django 5.1 on 2024-10-06 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_alter_message_options_messagereadtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='available_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Доступно до'),
        ),
        migrations.AddField(
            model_name='message',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Удалено'),
        ),
    ]
