# Generated by Django 5.1 on 2024-10-11 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0008_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='attachments',
            field=models.ManyToManyField(related_name='messages', to='chats.attachment'),
        ),
    ]
