# Generated by Django 5.1 on 2024-10-12 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0011_chat_expert'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='is_support',
            field=models.BooleanField(blank=True, default=False, verbose_name='Чат поддержки'),
        ),
    ]
