# Generated by Django 5.1 on 2024-10-14 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0014_attachment_filename'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={},
        ),
    ]
