# Generated by Django 5.1 on 2024-10-16 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0015_alter_attachment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={'verbose_name': 'Вложение', 'verbose_name_plural': 'Вложения'},
        ),
    ]
