# Generated by Django 5.1 on 2024-10-22 12:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0016_alter_attachment_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='confirmations',
            field=models.ManyToManyField(blank=True, related_name='confirmed_chats', to=settings.AUTH_USER_MODEL, verbose_name='Подтвердившие диалог'),
        ),
    ]
