# Generated by Django 5.1 on 2024-11-09 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0018_chat_declined_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='declined_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата отклонения'),
        ),
    ]
