# Generated by Django 5.1 on 2024-11-14 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0019_chat_declined_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата закрытия'),
        ),
    ]
